#!/usr/bin/env bash
# Build "Climaterisk.app" — a double-clickable macOS launcher for this checkout.
#
# The app starts the same two servers `run.command` starts (FastAPI backend + Vite
# frontend) and opens the UI in the default browser. Quitting the app (Cmd-Q, or the
# Dock icon's Quit) stops both. The repository itself is never modified — the app only
# points at it.
#
# It is built as a stay-open AppleScript applet wrapping a shell launcher, because a
# bare shell script in Contents/MacOS receives no Apple Events: Cmd-Q and Dock → Quit
# hang against such a bundle instead of shutting the servers down.
#
# Usage:  ./scripts/make_macos_app.command [destination-dir]
#         destination defaults to /Applications when writable, else ~/Applications.
#
# The generated app embeds THIS checkout's absolute path, so rebuild it after moving
# the repository. The builder itself contains no machine-specific paths.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_NAME="Climaterisk"
ICON_SRC="${REPO}/assets/app_icon.png"

DEST="${1:-}"
if [ -z "${DEST}" ]; then
  if [ -w /Applications ]; then DEST=/Applications; else DEST="${HOME}/Applications"; fi
fi
mkdir -p "${DEST}"
APP="${DEST}/${APP_NAME}.app"

for tool in sips iconutil osacompile; do
  command -v "${tool}" >/dev/null || { echo "!! ${tool} not found — this builder needs macOS." >&2; exit 1; }
done
[ -f "${ICON_SRC}" ] || { echo "!! icon source missing: ${ICON_SRC}" >&2; exit 1; }

echo "▶ repo:        ${REPO}"
echo "▶ destination: ${APP}"
WORK="$(mktemp -d)"; trap 'rm -rf "${WORK}"' EXIT

# ---- 1. the shell launcher (does the real work) ------------------------------------
cat > "${WORK}/launch.sh" <<'LAUNCHER'
#!/usr/bin/env bash
# Generated by scripts/make_macos_app.command — edit the builder, not this copy.
set -uo pipefail
REPO="__REPO_ROOT__"
LOG="${HOME}/Library/Logs/Climaterisk.log"
mkdir -p "$(dirname "${LOG}")"
exec >>"${LOG}" 2>&1
echo "=============== $(date '+%Y-%m-%d %H:%M:%S') launch ==============="

# A GUI launch inherits a minimal PATH; put the usual tool locations back.
export PATH="${HOME}/.local/bin:${HOME}/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:${PATH}"

alert() {
  echo "!! $1"
  /usr/bin/osascript -e "display alert \"Climaterisk\" message \"$1\" as critical" >/dev/null 2>&1 || true
  exit 1
}

cd "${REPO}" 2>/dev/null || alert "Project folder not found: ${REPO}. Rebuild the app with scripts/make_macos_app.command."
[ -f .env ] && { set -a; . ./.env; set +a; }

BACKEND_HOST="${CLIMATERISK_BACKEND_HOST:-127.0.0.1}"
BACKEND_PORT="${CLIMATERISK_BACKEND_PORT:-8099}"
FRONTEND_PORT="${CLIMATERISK_FRONTEND_PORT:-5174}"
FRONTEND_DIR="frontend/climaterisk"
WORKER_ENV_DIR="${CLIMATERISK_WORKER_ENV_DIR:-.climada-env}"
export CLIMATERISK_BACKEND_PORT CLIMATERISK_FRONTEND_PORT

cleanup() { echo "▶ shutting down…"; kill 0 2>/dev/null || true; }
trap cleanup EXIT INT TERM

command -v uv  >/dev/null || alert "'uv' not found. Install it (curl -LsSf https://astral.sh/uv/install.sh | sh) and try again."
command -v npm >/dev/null || alert "'npm' not found. Install Node.js (nodejs.org) and try again."

# Free the ports first: a previous launch, or run.command, may still hold them.
for port in "${BACKEND_PORT}" "${FRONTEND_PORT}"; do
  pids="$(lsof -ti "tcp:${port}" 2>/dev/null || true)"
  [ -n "${pids}" ] && kill ${pids} 2>/dev/null || true
done
pkill -f "uvicorn climaterisk.api.main:app" 2>/dev/null || true
sleep 0.5

# First launch after a fresh clone installs dependencies — minutes, so say so.
if [ ! -d ".venv" ] || [ ! -d "${FRONTEND_DIR}/node_modules" ]; then
  /usr/bin/osascript -e 'display notification "Installing dependencies — the first launch takes a few minutes." with title "Climaterisk"' >/dev/null 2>&1 || true
  [ -d ".venv" ] || uv sync --all-extras || alert "uv sync failed. See ${LOG}."
  [ -d "${FRONTEND_DIR}/node_modules" ] || ( cd "${FRONTEND_DIR}" && npm install ) || alert "npm install failed. See ${LOG}."
fi

[ -x "${WORKER_ENV_DIR}/bin/python" ] \
  && echo "▶ CLIMADA worker env ✓" \
  || echo "▶ CLIMADA worker env missing — physical-risk runs unavailable (build ./${WORKER_ENV_DIR} per the README)."

# App mode: no --reload. The reload watcher is a development aid and can orphan
# in-flight worker subprocesses when data/ is written during a run.
uv run uvicorn climaterisk.api.main:app --host "${BACKEND_HOST}" --port "${BACKEND_PORT}" &
( cd "${FRONTEND_DIR}" && npm run dev -- --port "${FRONTEND_PORT}" ) &

for _ in $(seq 1 90); do
  curl -fsS "http://${BACKEND_HOST}:${BACKEND_PORT}/api/health" >/dev/null 2>&1 && break
  sleep 0.5
done
curl -fsS "http://${BACKEND_HOST}:${BACKEND_PORT}/api/health" >/dev/null 2>&1 \
  || alert "The backend did not start within 45 s. See ${LOG}."

URL="http://localhost:${FRONTEND_PORT}"
for _ in $(seq 1 40); do curl -fsS "${URL}" >/dev/null 2>&1 && break; sleep 0.5; done
echo "▶ opening ${URL}"
open "${URL}"

wait
LAUNCHER
/usr/bin/sed -i '' "s|__REPO_ROOT__|${REPO}|" "${WORK}/launch.sh"

# ---- 2. the applet (owns the Dock tile and the quit event) -------------------------
cat > "${WORK}/applet.applescript" <<'APPLET'
-- Stay-open wrapper: starts the bundled launcher, keeps the app alive so macOS shows a
-- Dock tile with a working Quit, and shuts the servers down when the user quits.
property launcherPID : ""

on run
	set launcher to (POSIX path of (path to me)) & "Contents/Resources/launch.sh"
	try
		set launcherPID to (do shell script quoted form of launcher & " > /dev/null 2>&1 & echo $!")
	on error errText
		display alert "Climaterisk" message "Could not start: " & errText as critical
		quit
	end try
end run

on idle
	-- If the launcher died (a failed start, or the user killed it), don't leave an
	-- app in the Dock that controls nothing.
	if launcherPID is not "" then
		try
			do shell script "kill -0 " & launcherPID
		on error
			quit
		end try
	end if
	return 5
end idle

on quit
	if launcherPID is not "" then
		-- TERM reaches the launcher's trap, which stops the backend and the frontend.
		try
			do shell script "kill -TERM " & launcherPID & " 2>/dev/null || true"
		end try
		delay 1
	end if
	continue quit
end quit
APPLET

osacompile -o "${WORK}/${APP_NAME}.app" -s "${WORK}/applet.applescript"

# ---- 3. icon: PNG → .icns ----------------------------------------------------------
ICONSET="${WORK}/AppIcon.iconset"; mkdir -p "${ICONSET}"
for size in 16 32 128 256 512; do
  sips -z ${size} ${size}         "${ICON_SRC}" --out "${ICONSET}/icon_${size}x${size}.png"    >/dev/null
  sips -z $((size*2)) $((size*2)) "${ICON_SRC}" --out "${ICONSET}/icon_${size}x${size}@2x.png" >/dev/null
done
iconutil -c icns "${ICONSET}" -o "${WORK}/${APP_NAME}.app/Contents/Resources/applet.icns"

# ---- 4. assemble ------------------------------------------------------------------
install -m 755 "${WORK}/launch.sh" "${WORK}/${APP_NAME}.app/Contents/Resources/launch.sh"
VERSION="$(cd "${REPO}" && git describe --tags --always 2>/dev/null || date +%Y.%m.%d)"
PLIST="${WORK}/${APP_NAME}.app/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleName ${APP_NAME}"                          "${PLIST}" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :CFBundleDisplayName string ${APP_NAME}"            "${PLIST}" 2>/dev/null || \
/usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName ${APP_NAME}"                   "${PLIST}"
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier institute.planit.climaterisk"   "${PLIST}" 2>/dev/null || \
/usr/libexec/PlistBuddy -c "Add :CFBundleIdentifier string institute.planit.climaterisk" "${PLIST}"
/usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${VERSION}"       "${PLIST}" 2>/dev/null || \
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${VERSION}"             "${PLIST}"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${VERSION}"                        "${PLIST}" 2>/dev/null || true

rm -rf "${APP}"
mv "${WORK}/${APP_NAME}.app" "${APP}"
touch "${APP}"                      # nudge Finder to pick up the new icon

echo "▶ built ${APP}"
echo "  launch: double-click it in ${DEST} (or: open -a '${APP_NAME}')"
echo "  quit:   Cmd-Q, or the Dock icon → Quit — both stop the servers"
echo "  log:    ~/Library/Logs/Climaterisk.log"
